# Generated by Django 4.2.13 on 2024-07-09 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('estado_maquina_entrega', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('memoria_ram', models.IntegerField()),
                ('almacenamiento', models.IntegerField()),
                ('pantalla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bateria', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tamano_pantalla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('procesador', models.CharField(max_length=100)),
                ('generacion', models.CharField(max_length=50)),
                ('memoria_ram', models.IntegerField()),
                ('tipo_ram', models.CharField(max_length=50)),
                ('bus_ram', models.CharField(max_length=50)),
                ('tarjeta_grafica', models.CharField(max_length=100)),
                ('capacidad_tarjeta_grafica', models.IntegerField()),
                ('disco_hdd', models.IntegerField()),
                ('disco_ssd', models.IntegerField()),
                ('serial_cargador', models.CharField(max_length=100)),
                ('marca_cargador', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('generacion', models.CharField(max_length=50)),
                ('memoria_ram', models.IntegerField()),
                ('tipo_ram', models.CharField(max_length=50)),
                ('bus_ram', models.CharField(max_length=50)),
                ('tarjeta_grafica', models.CharField(max_length=100)),
                ('capacidad_tarjeta_grafica', models.IntegerField()),
                ('disco_hdd', models.IntegerField()),
                ('disco_ssd', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('estado_maquina_devolucion', models.CharField(max_length=100)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipos.asignacion')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.persona'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='equipo_celular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.celular'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='equipo_laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.laptop'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='equipo_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.pc'),
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_monitor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('modelo_monitor', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_teclado', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_mouse', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_celular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='equipos.celular')),
                ('equipo_laptop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='equipos.laptop')),
                ('equipo_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='equipos.pc')),
            ],
        ),
    ]
